routes/web.php
<?php

use App\Http\Controllers\Admin\RecruitmentNewsController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

// Will fix after creating admin site
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login'])->name('login');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::prefix('/admin')->name('admin.')->group(function () {

        Route::prefix('/recruitment-news')->name('news.')->group(function () {
            Route::get('/', [RecruitmentNewsController::class, 'index'])->name('list');
            Route::get('/delete/{id}', [RecruitmentNewsController::class, 'delete'])->name('delete');
            Route::post('/approve', [RecruitmentNewsController::class, 'approve'])->name('approve');
            Route::post('/create', [RecruitmentNewsController::class, 'create'])->name('create');
        });

    });
});

Route::get('/mailable', function () {
    $user = App\Models\User::find(1);

    Mail::to('dangvanhoa077@gmail.com')->send(new App\Mail\VerifyEmail($user));
    return new App\Mail\VerifyEmail($user);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/components/footer.blade.php
<footer class="footer text-center">
    2022 © Copyright VH
    {{-- <a href="https://www.wrappixel.com/">wrappixel.com</a> --}}
  </footer>

resources/views/admin/components/header.blade.php
 <!-- ============================================================== -->
      <!-- Topbar header - style you can find in pages.scss -->
      <!-- ============================================================== -->
      <header class="topbar" data-navbarbg="skin5">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
          <div class="navbar-header" data-logobg="skin6">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="dashboard.html">
              <!-- Logo icon -->
              <b class="logo-icon">
                <!-- Dark Logo icon -->
                <img src="{{asset('plugins/images/logo-icon.png')}}" alt="homepage" />
              </b>
              <!--End Logo icon -->
              <!-- Logo text -->
              <span class="logo-text">
                <!-- dark Logo text -->
                <img src="{{asset('plugins/images/logo-text.png')}}" alt="homepage" />
              </span>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <a
              class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
              href="javascript:void(0)"
              ><i class="ti-menu ti-close"></i
            ></a>
          </div>
          <!-- ============================================================== -->
          <!-- End Logo -->
          <!-- ============================================================== -->
          <div
            class="navbar-collapse collapse"
            id="navbarSupportedContent"
            data-navbarbg="skin5"
          >
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav ms-auto d-flex align-items-center">
              <!-- ============================================================== -->
              <!-- Search -->
              <!-- ============================================================== -->
              <li class="in">
                <form role="search" class="app-search d-none d-md-block me-3">
                  <input
                    type="text"
                    placeholder="Search..."
                    class="form-control mt-0"
                  />
                  <a href="" class="active">
                    <i class="fa fa-search"></i>
                  </a>
                </form>
              </li>
              <!-- ============================================================== -->
              <!-- User profile and search -->
              <!-- ============================================================== -->
              <li>
                <a class="profile-pic" href="#">
                  <img
                    src="{{auth()->user()->avatar ?? asset('plugins/images/users/varun.jpg')}}"
                    alt="user-img"
                    width="36"
                    class="img-circle"
                  /><span class="text-white font-medium">{{auth()->user()->name ?? 'Admin'}}</span></a
                >
              </li>
              <li class="mr-3">
                <a href="{{route('logout')}}" class=""><i class="fas fa-sign-out-alt"></i></a>
              </li>

              <!-- ============================================================== -->
              <!-- User profile and search -->
              <!-- ============================================================== -->
            </ul>
          </div>
        </nav>
      </header>
      <!-- ============================================================== -->
      <!-- End Topbar header -->
      <!-- ============================================================== -->

resources/views/admin/components/sidebar.blade.php
<!-- ============================================================== -->
      <!-- Left Sidebar - style you can find in sidebar.scss  -->
      <!-- ============================================================== -->
      <aside class="left-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
          <!-- Sidebar navigation-->
          <nav class="sidebar-nav">
            <ul id="sidebarnav">
              <!-- User Profile-->
              <li class="sidebar-item pt-2">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="{{route('home')}}"
                  aria-expanded="false"
                >
                  <i class="far fa-clock" aria-hidden="true"></i>
                  <span class="hide-menu">Dashboard</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="profile.html"
                  aria-expanded="false"
                >
                  <i class=" fas fa-user-secret" aria-hidden="true"></i>
                  <span class="hide-menu">Nhà tuyển dụng</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="profile.html"
                  aria-expanded="false"
                >
                  <i class="fa fa-user" aria-hidden="true"></i>
                  <span class="hide-menu">Sinh viên</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="{{route('admin.news.list')}}"
                  aria-expanded="false"
                >
                  <i class="fa fa-columns" aria-hidden="true"></i>
                  <span class="hide-menu">Tin tuyển dụng</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="basic-table.html"
                  aria-expanded="false"
                >
                  <i class="fa fa-table" aria-hidden="true"></i>
                  <span class="hide-menu">Danh mục công việc</span>
                </a>
              </li>
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="fontawesome.html"
                  aria-expanded="false"
                >
                  <i class="fa fa-font" aria-hidden="true"></i>
                  <span class="hide-menu">Report tin tuyển dụng</span>
                </a>
              </li>
              {{-- <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="map-google.html"
                  aria-expanded="false"
                >
                  <i class="fa fa-globe" aria-hidden="true"></i>
                  <span class="hide-menu">Google Map</span>
                </a>
              </li> --}}
             
              {{-- <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="404.html"
                  aria-expanded="false"
                >
                  <i class="fa fa-info-circle" aria-hidden="true"></i>
                  <span class="hide-menu">Error 404</span>
                </a>
              </li> --}}
            </ul>
          </nav>
          <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
      </aside>
      <!-- ============================================================== -->
      <!-- End Left Sidebar - style you can find in sidebar.scss  -->
      <!-- ============================================================== -->